version: '2'

services:
  mongo-express:
    image: mongo-express
    container_name: mongo-express-container
    ports:
      - 8080:8081
    environment:
      # ME_CONFIG_BASICAUTH_USERNAME: user
      # ME_CONFIG_BASICAUTH_PASSWORD: user
      ME_CONFIG_MONGODB_PORT: 27017
      # ME_CONFIG_MONGODB_ADMINUSERNAME: root
      # ME_CONFIG_MONGODB_ADMINPASSWORD: root
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo-container
    restart: always
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - $PWD/data/db:/data/db
      - $PWD/dumps:/dumps

  node:
    build: backend/
    container_name: node-container
    restart: always
    command: npm start --silent
    environment: 
      - NODE_ENV=production
    volumes: 
      - ./backend:/home/node/app
      - /home/node/app/node_modules
    ports:  
      - "8081:8081"
    # dns: 
    #  - 200.129.79.61
    depends_on:
      - mongo